services:
    ok99.privatezone.user.form.type.user_avatar:
        class: Ok99\PrivateZoneCore\UserBundle\Form\UserAvatarType
        tags:
            - { name: form.type, alias: user_avatar }

    ok99.privatezone.user.form.type.user_photo:
        class: Ok99\PrivateZoneCore\UserBundle\Form\UserPhotoType
        tags:
            - { name: form.type, alias: user_photo }

    ok99.privatezone.user.form.type.user_performance_groups:
        class: Ok99\PrivateZoneCore\UserBundle\Form\UserPerformanceGroupsType
        tags:
            - { name: form.type, alias: user_performance_groups }

    ok99.privatezone.user.form.type.user_training_groups:
        class: Ok99\PrivateZoneCore\UserBundle\Form\UserTrainingGroupsType
        tags:
            - { name: form.type, alias: user_training_groups }
